// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccD9MhPKPet4jL_pysL2P_DuP0QC-Qrc',
    appId: '1:156858555530:web:17fd4d47231dcfa9cee173',
    messagingSenderId: '156858555530',
    projectId: 'explorex-2026',
    authDomain: 'explorex-2026.firebaseapp.com',
    storageBucket: 'explorex-2026.firebasestorage.app',
    measurementId: 'G-55HBLV9470',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoLAC3yD3OcqTdZjAEKjPeVZJUEyJ2P4',
    appId: '1:156858555530:android:ef86813bd45ec623cee173',
    messagingSenderId: '156858555530',
    projectId: 'explorex-2026',
    storageBucket: 'explorex-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFL20S6ksdQFaF5l6XkWUALSQ8rrS-ok',
    appId: '1:156858555530:ios:f7a0ac2b4e7b9d11cee173',
    messagingSenderId: '156858555530',
    projectId: 'explorex-2026',
    storageBucket: 'explorex-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFL20S6ksdQFaF5l6XkWUALSQ8rrS-ok',
    appId: '1:156858555530:ios:f7a0ac2b4e7b9d11cee173',
    messagingSenderId: '156858555530',
    projectId: 'explorex-2026',
    storageBucket: 'explorex-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAccD9MhPKPet4jL_pysL2P_DuP0QC-Qrc',
    appId: '1:156858555530:web:9f852f83ba97c872cee173',
    messagingSenderId: '156858555530',
    projectId: 'explorex-2026',
    authDomain: 'explorex-2026.firebaseapp.com',
    storageBucket: 'explorex-2026.firebasestorage.app',
    measurementId: 'G-PZ77D1QTSE',
  );

}
